//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GanttEntities : DbContext
    {
        private volatile Type _dependency;
        public GanttEntities()
            : base("name=GanttEntities")
        {
            _dependency = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dependency> Dependencies { get; set; }
        public virtual DbSet<ResourceAssignment> ResourceAssignments { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    }
}
